### PR TITLE
[enhancement] Valuemapping

### PR DESCRIPTION
**Pull request by radeksvarz**
I added the callback function for value mapping to different representation in the "thumb".

### CODE REVIEW

**Comment by rvamsikrishna** [comment]
Thanks for show interest in the package and submitting the PR. But can you explain what the mapping could add to the current functionality? Do you have any example her case you came across?

**Comment by radeksvarz** [comment]
It allows rendering the mapped representation of the values into the thumb. 

The code example is mentioned in the README. 

Here is the visual example.

value_slider

**Comment by radeksvarz** [comment]
I also thought about implementing similar callback asking for Widget which would allow to map e.g. icons.

**Comment by rvamsikrishna** [comment]
Cool! got it.

**Pull request merged**
